source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target 'JustTweak_Example' do
  pod 'JustTweak', :path => '../'
  pod 'Firebase/RemoteConfig'
  pod 'OptimizelySDKiOS'

  target 'JustTweak_Tests' do
    inherit! :search_paths
  end
end
