source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'JustTweak_Example' do
  pod 'JustTweak', :path => '../'
  pod 'Firebase/RemoteConfig'

  target 'JustTweak_Tests' do
    inherit! :search_paths
  end
end
